language: node_js
node_js:
  - "0.10"
python:
  - "2.7"
servies:
  - rabbitmq
  - mongodb
before_script:
  - "chmod +x ./.ci.sh; source .ci.sh"
  - "npm i -g jasmine-node"
  - "npm i -g jasmine-jquery"
  - "npm i -g brunch"
  - "sudo apt-get update"
  - "sudo apt-get install libevent-dev"
  - "sudo apt-get install supervisor"
  - "sudo apt-get install python-dev"
  - "sudo apt-get install python-setuptools"
  - "sudo apt-get install python-pip"
  - "sudo apt-get install build-essential"
  - "sudo apt-get install python-gevent"
  - "sudo apt-get install libevent-dev"
  - "sudo apt-get install supervisor"
  - "sudo apt-get install swig"
  - "sudo apt-get install libvpx-dev"
  - "sudo apt-get install subversion"
  - "sudo apt-get install python-pastescript"
  - "sudo apt-get install ipython"
  - "sudo apt-get install python-opencv"
  - "sudo apt-get install python-scipy"
  - "sudo apt-get install python-numpy"
  - "sudo apt-get install python-pygame"
  - "sudo apt-get install libamd2.2.0"
  - "sudo apt-get install libblas3gf"
  - "sudo apt-get install libc6"
  - "sudo apt-get install libgcc1"
  - "sudo apt-get install libgfortran3"
  - "sudo apt-get install liblapack3gf"
  - "sudo apt-get install libumfpack5.4.0"
  - "sudo apt-get install libstdc++6"
  - "sudo apt-get install build-essential"
  - "sudo apt-get install gfortran"
  - "sudo apt-get install python-all-dev"
  - "sudo apt-get install libsdl1.2-dev"
  - "sudo apt-get install libsmpeg-dev"
  - "sudo pip install pandas"
  - "sudo pip install patsy==0.1.0"
  - "git submodule init"
  - "git submodule update"
  - "cd SimpleSeer; git pull; cd .."
  - "cd SeerCloud; git pull; cd .."
  - "sudo pip install -r SimpleSeer/pip.requirements"
  - "sudo pip install gevent"
  - "sudo pip install path.py"
  - "sudo pip install python-dateutil"
  - "sudo pip install svgwrite"
  - "sudo pip install pyyaml"
  - "sudo pip install mongoengine"
  - "sudo apt-get install python-pygame"
  - "sudo pip install PIL"
  - "sudo apt-get install python-opencv"
  - "sudo pip install jsonpickle"
  - "sudo pip install https://github.com/sightmachine/SimpleCV/zipball/develop"
  - "sudo pip install flask"
  - "sudo pip install pytz"
  - "sudo pip install amqplib"
  - "sudo pip install gevent-socketio==0.3.5-beta"
  - "sudo apt-get install phantomjs"
  - "mkdir -p /tmp/mongo;wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-2.2.0.tgz -O /tmp/mongodb-linux-x86_64-2.2.0.tgz;sudo tar zxvf /tmp/mongodb-linux-x86_64-2.2.0.tgz -C /tmp/mongo;sudo cp /tmp/mongo/mongodb-linux-x86_64-2.2.0/bin/* /usr/local/bin/;sudo mkdir -p /var/lib/mongodb;sudo mkdir -p /var/log/mongodb;sudo cp ./SimpleSeer/etc/mongodb.conf /etc/"
  - "cd SimpleSeer; sudo python setup.py develop; cd ../"
  - "cd SeerCloud; sudo python setup.py develop; cd ../"
  - "sudo simpleseer deploy"
  - "sudo mongod --fork --config /etc/mongodb.conf"
  - "sudo rabbitmq-server &"
  - "pip freeze | grep Seer"
  - "simpleseer build"
script:
  - "simpleseer test"
source_key: "LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb2dJQkFBS0NBUUVBeDRBOERFTnVLYW90UkZnWUxzSGVxQXk2aDlZb1YwR0pNUDRvazl0OHlZZUROcTRtCmZLMnpiTEVTZHg1d2psQ3ZFQ0V0UEdvdnp1My9ZR2Jtc25YTnNJTUgzNU1JVzFydmNzOFJPYXZ5ZUdld3RvaloKdndaK3g3U2JneFNoTGlLTklZeUR4S05Wa3dvcXpLNEdGcXdGTWM4djFVSVJJMHVyMTFDOFJXYU44VzRpOVB1bQpaY1RLQmdSN3FaMWhRY1ZsMzRQMWhOMUVvUGhHcHVMeSs4TVhYUXZIRzJoR2k4U1g4MjBPMWVJTlpKckNrMFE3CmgvM1RwT01YeE1zK1g3cXpDYk5rYjhISE1SL1J0VXNJNG9OUkZSenEzNjRFbGRRVmdJdnpTMytKdzB3dFlVd3AKUGYwRWE5anhXejVwZ0Y3MFlXMWRON1NYZmhRdGJxVEdQTlk5NlFJREFRQUJBb0lCQUVudHpWTEdFaWJDZDIvaQpMV1AyVitweWZSVWxXV0dzV1lpY1JyRTBIdlFYa1pwTHd0dGxDeDUySjkrWW1pRkM2UHpUTG80NjAyaWRiWXR0CjFvTy9mKyt2UHRXdENPWEJ0d1lXa2MyTFdKa2g0NnhnM2tBWnloVjdhajJUQVgrMU1oT0NuTG5ieFRSdUNobzcKU3VwUDZNVGlnRmxJMkV6NkY3MzhueWdncnUwT09NWmNyenlKVTUrN2E4UkFwWTVScWRJRWtGVEdiRncyM2pJVgplNTBRajhVZ0JiWVF4dGFkSCtzSGRVVjhyREg1b0dxNHowOVBMblpmTStMQ1RDK2Yvd1dETVJOclpySzBUN0VjCnFvQ3VmRkJEd1RyQTBrRStzR2RsK1NtWCtxcHpISU43ZHFtTjBZWWEvdVZZdEtIMnU3MFhlOGVEcGEwTksrcVMKOFIwbE53RUNnWUVBL0ZzZnVheVM1WS9ZTkJZempKeC9hSDVGODRJdzZYMzR4Nmw5ZGNhMGxzbEFPYmpXYkZvQgo3R2dzbjBsRTJtSlY4MmhqNU9BdmsvYWV5ckFMaDN2Vi85b09SSFRTM0RwV3VsNkFmRVJVMmVnUEs5cFJpUERzCkNSYWZTbDlsQjdzNVhHZk9tS1VyWkxWQXk4MGJsOXVXWEtzNmlaaEhGUWZGVFZvdXQvUVhibkVDZ1lFQXltRzUKSDFRa2RpQzNWNm80U2lzTUxtREdQSnJGejZ2L2FFdWlzWkhHSGx2dUEwRVFyRGlCME9EMUFEUm9PU2h6U29sSwpScGIwdEhXUE9XUUphRkZwdUtGbTNQNzBkaEFIL3Zsa3lqOXRtSS9vTHVYNEwwNGZYeU9YTCtUOG9jRnVBZUQ0CjVNUmVrVVhYZk9VUHpaYS80NHUvVkdjZm5xbWlWRVFlWmxKMTh2a0NnWUFYZXhzZW1iSXBiaEw5OWJyaU1JV2kKWVcxODFQWmNJMzZNaFhiSkNLNHhBWlRhU2hxWmhsNTdjczRFSERzdDNzeUVrNGdIK2R3emRsVWNJdmxQcC9RbgpsRkNUaWhNOHJxajNPbWZXS0QyRThSVElUYzRjWWQ1MGtnaE1VVWdEU2laeU5LNkNnWXZpR1FOb2N6TklGQVNQCnB0Y1JpbnZDdHpCaW5DdVFya09uNFFLQmdBeDNhcFRnZFFLRnoyVnFDZCtmdVRkZUpMZjAvTHhuSnV1QXhUdlUKOC9SSXkyZU42WDRDV1JUSjFxMjFqTG9Bb09GMWhZckZuN3RDQnBtTmJQcnRFT3Nibmg5ODRRZ293cVZWTFgwNwozUDlwMWU2Vm9lMGdEZFNwZDVXdXNGVXllaGxKaDJ0b0lUOG5vemVCVUxEa1dWdWw3eG8rNC9hOUVrL0lobXJkCko0RFpBb0dBRWtubDQ1WjMrdi93Q1d2WVIxeUpvTXdsTXMzM0YrSWJDQm0yTitWd0oxOFZqTHJ3Uko3OWc4V3QKdk1NM0dGT1B5V25vM0JvYlVHQ2xqUG9UckN0ZWFJSk53dm5DUjBKTVFibUZMK0JXbmdJZ2NHSDZOL1VGaU5MbwpSTnJMb2xENkRVZTRjZmIzNytWdnJSN2JNMEJLTlZUenFTdTFyUUtpR001SFQ1S1p5TzA9Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg=="
